ntpd: F: Add support for monitoring via Prometheus node_exporter (textfile_collector)

diff --git a/ntpd/templates/main/ntpd_check-time.sh.j2 b/ntpd/templates/main/ntpd_check-time.sh.j2
--- a/ntpd/templates/main/ntpd_check-time.sh.j2
+++ b/ntpd/templates/main/ntpd_check-time.sh.j2
@@ -62,6 +62,7 @@ severity='Debug'
 message='Please check log files for more information.'
 
 offset_limit='{{ntpd_check_time_offset_limit}}'
+textfile_collector='{{ntpd_monitor_prom_textfile_collector}}'
 
 {% if (ntpd_monitor_mail_state is match('true|yes|enable')) %}
 mail_from_address='{{ntpd_monitor_mail_from_address}}'
@@ -105,6 +106,44 @@ FQDN        : {{ansible_fqdn}}"
 }
 {% endif %}
 
+{% if (ntpd_monitor_prom_state is match('true|yes|enable')) %}
+update_prom() {
+  retval="$1"
+  time_start="$2"
+  time_exec="$3"
+
+  if [ -w "${textfile_collector}" ]; then
+    ${echo} -e "# HELP ntpd_check_time_exit The script's exit code.\n"\
+"# TYPE ntpd_check_time_exit counter\n"\
+"ntpd_check_time_exit ${retval}" > "${textfile_collector}/ntpd_check_time_exit.prom"
+
+    if [ -z "${time_start}" ] ; then
+      ${rm} -f "${textfile_collector}/ntpd_check_time_start.prom"
+    else
+      ${echo} -e "# HELP ntpd_check_time_start The script's start time in epoch.\n"\
+"# TYPE ntpd_check_time_start counter\n"\
+"ntpd_check_time_start ${time_start}" > "${textfile_collector}/ntpd_check_time_start.prom"
+    fi
+
+    if [ -z "${time_exec}" ] ; then
+      ${rm} -f "${textfile_collector}/ntpd_check_time_duration.prom"
+    else
+      ${echo} -e "# HELP ntpd_check_time_duration The script's execution duration in seconds.\n"\
+"# TYPE ntpd_check_time_duration counter\n"\
+"ntpd_check_time_duration ${time_exec}" > "${textfile_collector}/ntpd_check_time_duration.prom"
+    fi
+
+    if [ -z "${offset_raw}" ] ; then
+      ${rm} -f "${textfile_collector}/ntpd_check_time_offset.prom"
+    else
+      ${echo} -e "# HELP ntpd_check_time_offset The system time offset in milliseconds.\n"\
+"# TYPE ntpd_check_time_offset counter\n"\
+"ntpd_check_time_offset{limit=\"${offset_limit}\"} ${offset_raw}" > "${textfile_collector}/ntpd_check_time_offset.prom"
+    fi
+  fi
+}
+{% endif %}
+
 check_script_user() {
   if [ "$(${whoami})" != "${user}" ]; then
     retval=77
@@ -137,13 +176,21 @@ log_and_exit_on_error() {
   message="$3"
   if [ "${retval}" -ne 0 ]; then
     ${rm} -f "${lockfile}"
+
     if [ -t 1 ] ; then
       ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
     fi
+
     ${logger} -t "${script}" "${severity}: ${message}"
+
 {% if (ntpd_monitor_mail_state is match('true|yes|enable')) %}
     mail_error "${retval}" "${severity}" "${message}"
 {% endif %}
+
+{% if (ntpd_monitor_prom_state is match('true|yes|enable')) %}
+    update_prom "${retval}" "${time_start}" "${time_exec}"
+{% endif %}
+
     exit "${retval}"
   fi
 }
@@ -157,6 +204,10 @@ log_and_exit() {
   severity='Info'
   message='System time is synchronized.'
   ${logger} -t "${script}" "${severity}: ${message} Duration: ${time_hr}"
+
+{% if (ntpd_monitor_prom_state is match('true|yes|enable')) %}
+  update_prom "${retval}" "${time_start}" "${time_exec}"
+{% endif %}
 
   exit "${retval}"
 }
@@ -191,14 +242,18 @@ time_initial=0
 watch_and_wait_for_change "${ntpstat}" 'unsynchronised' '' '2' '32'
 
 # Get system time offset
-offset=$(${ntpq} -c rv | ${sed} -n 's@.*offset=\([-0-9]*\).*@\1@p' | ${tr} -d '-')
+offset_raw=$(${ntpq} -c rv | ${sed} -n 's@.*offset=\([-0-9.]*\).*@\1@p')
 log_and_exit_on_error "$?" 'Error' 'Unable to get system time offset.'
+
+# Convert system time offset
+offset=$(${echo} "${offset_raw}" | ${sed} -n 's@[.].*@@p' | ${tr} -d '-')
+log_and_exit_on_error "$?" 'Error' 'Unable to convert system time offset.'
 
 # Check system time offset
 if [ -z "${offset}" ] ; then
   log_and_exit_on_error '1' 'Error' 'System time is not synchronized with any peer.'
 elif [ "${offset}" -ge "${offset_limit}" ]; then
-  log_and_exit_on_error '1' 'Error' "System time offset limit exceeded (${offset}/${offset_limit} ms)."
+  log_and_exit_on_error '1' 'Error' "System time offset limit exceeded (${offset} ms / ${offset_limit} ms)."
 fi
 
 remove_lockfile
