ntpd: C: Redesign role to support SELinux

diff --git a/ntpd/templates/main/ntpd_check-time.j2 b/ntpd/templates/main/ntpd_check-time.j2
--- a/ntpd/templates/main/ntpd_check-time.j2
+++ b/ntpd/templates/main/ntpd_check-time.j2
@@ -8,7 +8,7 @@
 # INFORMATION
 #-------------------------------------------------------------------------------
 #
-# Name   : ntpd_update-time.sh
+# Name   : ntpd_check-time
 # Type   : Shell script
 # Role   : ntpd
 #
@@ -33,16 +33,19 @@ basename=$(${which} basename) || { echo "Error: Command 'basename' not found."; 
 date=$(${which} date) || { echo "Error: Command 'date' not found."; exit 127; }
 echo=$(${which} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
 expr=$(${which} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
+grep=$(${which} grep) || { echo "Error: Command 'grep' not found."; exit 127; }
 hostname=$(${which} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
 logger=$(${which} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
 {% if (ntpd_monitor_mail_state is match('true|yes|enable')) %}
 mailx=$(${which} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
 {% endif %}
+ntpq=$(${which} ntpq) || { echo "Error: Command 'ntpq' not found."; exit 127; }
+ntpstat=$(${which} ntpstat) || { echo "Error: Command 'ntpstat' not found."; exit 127; }
 rm=$(${which} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
+sed=$(${which} sed) || { echo "Error: Command 'sed' not found."; exit 127; }
+sleep=$(${which} sleep) || { echo "Error: Command 'sleep' not found."; exit 127; }
 touch=$(${which} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
 whoami=$(${which} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
-
-ntpd='{{ntpd}}'
 
 #-------------------------------------------------------------------------------
 # VARIABLES
@@ -51,19 +54,19 @@ ntpd='{{ntpd}}'
 host=$(${hostname} -s) || { echo "Error: Host name unknown."; exit 68; }
 script="$(${basename} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
 time_start=$(${date} '+%s')
-user='{{file_owner_ntpd_update_time_sh}}'
-lockfile='{{file_dst_ntpd_script_dir}}/ntpd_update-time.lock'
+user='{{file_owner_ntpd_check_time}}'
+lockfile='/var/tmp/ntpd_check-time.lock'
 retval=0
 severity='Debug'
 message='Please check log files for more information.'
 
-ntpd_servers='{% for item in ntpd_server %}{{item.address}}{% if not loop.last %} {% endif %}{% endfor %}'
+offset_limit='{{ntpd_check_time_offset_limit}}'
 textfile_collector='{{ntpd_monitor_prom_textfile_collector}}'
 
 {% if (ntpd_monitor_mail_state is match('true|yes|enable')) %}
 mail_from_address='{{ntpd_monitor_mail_from_address}}'
 mail_to_address='{% for item in ntpd_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
-mail_subject='ntpd: Update Time - Error ({{ansible_hostname}})'
+mail_subject='ntpd: Check Time - Error ({{ansible_hostname}})'
 {% endif %}
 
 #-------------------------------------------------------------------------------
@@ -87,7 +90,7 @@ Date & Time : $(${date} '+%Y-%m-%dT%H:%M:%S%z')
 SCRIPT
 --------------------------------------------------------------------------------
 
-Name        : ntpd_update-time.sh
+Name        : ntpd_check-time
 Type        : Shell script
 PID         : $$
 
@@ -109,24 +112,32 @@ update_prom() {
   time_exec="$3"
 
   if [ -w "${textfile_collector}" ]; then
-    ${echo} -e "# HELP ntpd_update_time_exit The script's exit code.\n"\
-"# TYPE ntpd_update_time_exit counter\n"\
-"ntpd_update_time_exit ${retval}" > "${textfile_collector}/ntpd_update_time_exit.prom"
+    ${echo} -e "# HELP ntpd_check_time_exit The script's exit code.\n"\
+"# TYPE ntpd_check_time_exit counter\n"\
+"ntpd_check_time_exit ${retval}" > "${textfile_collector}/ntpd_check_time_exit.prom"
 
     if [ -z "${time_start}" ] ; then
-      ${rm} -f "${textfile_collector}/ntpd_update_time_start.prom"
+      ${rm} -f "${textfile_collector}/ntpd_check_time_start.prom"
     else
-      ${echo} -e "# HELP ntpd_update_time_start The script's start time in epoch.\n"\
-"# TYPE ntpd_update_time_start counter\n"\
-"ntpd_update_time_start ${time_start}" > "${textfile_collector}/ntpd_update_time_start.prom"
+      ${echo} -e "# HELP ntpd_check_time_start The script's start time in epoch.\n"\
+"# TYPE ntpd_check_time_start counter\n"\
+"ntpd_check_time_start ${time_start}" > "${textfile_collector}/ntpd_check_time_start.prom"
     fi
 
     if [ -z "${time_exec}" ] ; then
-      ${rm} -f "${textfile_collector}/ntpd_update_time_duration.prom"
+      ${rm} -f "${textfile_collector}/ntpd_check_time_duration.prom"
     else
-      ${echo} -e "# HELP ntpd_update_time_duration The script's execution duration in seconds.\n"\
-"# TYPE ntpd_update_time_duration counter\n"\
-"ntpd_update_time_duration ${time_exec}" > "${textfile_collector}/ntpd_update_time_duration.prom"
+      ${echo} -e "# HELP ntpd_check_time_duration The script's execution duration in seconds.\n"\
+"# TYPE ntpd_check_time_duration counter\n"\
+"ntpd_check_time_duration ${time_exec}" > "${textfile_collector}/ntpd_check_time_duration.prom"
+    fi
+
+    if [ -z "${offset_raw}" ] ; then
+      ${rm} -f "${textfile_collector}/ntpd_check_time_offset.prom"
+    else
+      ${echo} -e "# HELP ntpd_check_time_offset The system time offset in milliseconds.\n"\
+"# TYPE ntpd_check_time_offset counter\n"\
+"ntpd_check_time_offset{limit=\"${offset_limit}\"} ${offset_raw}" > "${textfile_collector}/ntpd_check_time_offset.prom"
     fi
   fi
 }
@@ -190,7 +201,7 @@ log_and_exit() {
 
   retval=0
   severity='Info'
-  message='System time and hardware clock updated.'
+  message='System time is synchronized.'
   ${logger} -t "${script}" "${severity}: ${message} Duration: ${time_hr}"
 
 {% if (ntpd_monitor_prom_state is match('true|yes|enable')) %}
@@ -198,6 +209,23 @@ log_and_exit() {
 {% endif %}
 
   exit "${retval}"
+}
+
+watch_and_wait_for_change() {
+  watch_key="$1"
+  watch_value="$2"
+  watch_option="$3"
+  time_step="$4"
+  time_maximum="$5"
+  while ${watch_key} | ${grep} ${watch_option} "${watch_value}" > /dev/null 2>&1 ; do
+    log_and_exit_on_error "$?" 'Error' 'Unable to get system time status.'
+    if [ "${time_initial}" -lt "${time_maximum}" ]; then
+      time_initial=$(${expr} "${time_initial}" + "${time_step}")
+      ${sleep} "${time_initial}"
+    else
+    log_and_exit_on_error "1" 'Error' 'System time is not synchronized.'
+    fi
+  done
 }
 
 #-------------------------------------------------------------------------------
@@ -208,17 +236,24 @@ check_script_user
 
 create_lockfile
 
-# Update the system time by polling NTP servers
-for ntpd_server in ${ntpd_servers} ; do
-  ${ntpd} ${ntpd_server} > /dev/null 2>&1
-  if [ "$?" -eq 0 ]; then
-    ntpd_status=0
-    break;
-  else
-    ntpd_status=1
-  fi
-done
-log_and_exit_on_error "${ntpd_status}" 'Error' 'Unable to update the system time.'
+# Get system time status and wait while 'unsynchronised'
+time_initial=0
+watch_and_wait_for_change "${ntpstat}" 'unsynchronised' '' '2' '32'
+
+# Get system time offset
+offset_raw=$(${ntpq} -c rv | ${sed} -n 's@.*offset=\([-0-9.]*\).*@\1@p')
+log_and_exit_on_error "$?" 'Error' 'Unable to get system time offset.'
+
+# Convert system time offset
+offset=$(${echo} "${offset_raw}" | ${sed} -n 's@[.].*@@p' | ${sed} 's@[+-]@@g')
+log_and_exit_on_error "$?" 'Error' 'Unable to convert system time offset.'
+
+# Check system time offset
+if [ -z "${offset}" ] ; then
+  log_and_exit_on_error '1' 'Error' 'System time is not synchronized with any peer.'
+elif [ "${offset}" -ge "${offset_limit}" ]; then
+  log_and_exit_on_error '1' 'Error' "System time offset limit exceeded (${offset} ms / ${offset_limit} ms)."
+fi
 
 remove_lockfile
 
