postgresql: E: Improve Shell script to prevent globbing and word splitting

diff --git a/postgresql/templates/main/postgresql_run-backup.sh.j2 b/postgresql/templates/main/postgresql_run-backup.sh.j2
--- a/postgresql/templates/main/postgresql_run-backup.sh.j2
+++ b/postgresql/templates/main/postgresql_run-backup.sh.j2
@@ -50,7 +50,6 @@ touch=$(${which} touch) || { echo "Error: Command 'touch' not found."; exit 127;
 whoami=$(${which} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
 
 pg_dump=$(${which} pg_dump) || { echo "Error: Command 'pg_dump' not found."; exit 127; }
-postgres=$(${which} postgres) || { echo "Error: Command 'postgres' not found."; exit 127; }
 psql=$(${which} psql) || { echo "Error: Command 'psql' not found."; exit 127; }
 
 #-------------------------------------------------------------------------------
@@ -59,7 +58,6 @@ psql=$(${which} psql) || { echo "Error: Command 'psql' not found."; exit 127; }
 
 host=$(${hostname} -s) || { echo "Error: Host name unknown."; exit 68; }
 script="$(${basename} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
-date_start=$(${date} '+%Y-%m-%dT%H:%M:%S%z')
 time_start=$(${date} '+%s')
 user='{{file_owner_postgresql_run_backup_sh}}'
 lockfile='{{file_dst_postgresql_script_dir}}/postgresql_run-backup.lock'
@@ -68,7 +66,6 @@ severity='Debug'
 message='Please check log files for more information.'
 
 postgresql_service_name='{{service_name_postgresql}}'
-postgresql_conf='{{file_dst_postgresql_conf}}'
 postgresql_host='localhost'
 postgresql_username='postgres'
 postgresql_password='{{postgresql_postgres_password}}'
@@ -128,22 +125,22 @@ check_script_user() {
     retval=77
     severity='Error'
     message="Please run script as user '${user}'"
-    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: "${severity}: ${message}""
-    exit ${retval}
+    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
+    exit "${retval}"
   fi
 }
 
 create_lockfile() {
-  if [ ! -e ${lockfile} ]; then
-    ${touch} ${lockfile} || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
+  if [ ! -e "${lockfile}" ]; then
+    ${touch} "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
   else
     log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
   fi
 }
 
 remove_lockfile() {
-  if [ -e ${lockfile} ]; then
-    ${rm} -f ${lockfile} || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
+  if [ -e "${lockfile}" ]; then
+    ${rm} -f "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
   else
     log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
   fi
@@ -153,29 +150,28 @@ log_and_exit_on_error() {
   retval=$1
   severity=$2
   message=$3
-  if [ ${retval} -ne 0 ]; then
+  if [ "${retval}" -ne 0 ]; then
     ${rm} -f ${lockfile}
-    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: "${severity}: ${message}""
-    ${logger} -t ${script} "${severity}: ${message}"
+    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
+    ${logger} -t "${script}" "${severity}: ${message}"
 {% if (postgresql_monitor_mail_state is match('true|yes|enable')) %}
-    mail_error ${retval} "${severity}" "${message}"
+    mail_error "${retval}" "${severity}" "${message}"
 {% endif %}
-    exit ${retval}
+    exit "${retval}"
   fi
 }
 
 log_and_exit() {
-  date_end=$(${date} '+%Y-%m-%dT%H:%M:%S%z')
   time_end=$(${date} '+%s')
-  time_exec=$(${expr} ${time_end} - ${time_start})
+  time_exec=$(${expr} "${time_end}" - "${time_start}")
   time_hr=$(${date} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
 
   retval=0
   severity='Info'
   message='Backup created successfully.'
-  ${logger} -t ${script} "${severity}: ${message} Duration: ${time_hr}"
+  ${logger} -t "${script}" "${severity}: ${message} Duration: ${time_hr}"
 
-  exit ${retval}
+  exit "${retval}"
 }
 
 #-------------------------------------------------------------------------------
@@ -197,25 +193,25 @@ log_and_exit_on_error "$?" 'Error' 'Unable to get individual PostgreSQL database
 # Dump and compress individual PostgreSQL databases
 for db in ${databases} ; do
   ${su} ${postgresql_username} -c "PGPASSWORD=${postgresql_password} ${pg_dump} -h ${postgresql_host} -U ${postgresql_username} -Fp ${db} | ${gzip} -c > ${backup_dir}/${host}_${db}_${backup_timestamp}.gz"
-  if [ "$?" -eq '0' ]; then
+  if [ "$?" -eq 0 ]; then
     severity='Info'
     message="'${db}' dumped and compressed."
-    ${logger} -t ${script} "${severity}: ${message}"
+    ${logger} -t "${script}" "${severity}: ${message}"
   else
     log_and_exit_on_error "$?" 'Error' "Unable to dump and compress '${db}'."
   fi
 done
 
 # Ensure proper file owner and group
-${find} ${backup_dir} -type f -name "${host}_*_${backup_timestamp}.gz" -exec ${chown} ${backup_file_owner}:${backup_file_group} '{}' ';'
+${find} "${backup_dir}" -type f -name "${host}_*_${backup_timestamp}.gz" -exec ${chown} ${backup_file_owner}:${backup_file_group} '{}' ';'
 log_and_exit_on_error "$?" 'Error' 'Unable to ensure proper file owner and group.'
 
 # Ensure proper file permission
-${find} ${backup_dir} -type f -name "${host}_*_${backup_timestamp}.gz" -exec ${chmod} ${backup_file_mode} '{}' ';'
+${find} "${backup_dir}" -type f -name "${host}_*_${backup_timestamp}.gz" -exec ${chmod} ${backup_file_mode} '{}' ';'
 log_and_exit_on_error "$?" 'Error' 'Unable to ensure proper file permission.'
 
 # Remove old PostgreSQL database dumps
-${find} ${backup_dir} -type f -name "${host}_*.gz" -mtime +${keep_days} -exec ${rm} -f '{}' ';'
+${find} "${backup_dir}" -type f -name "${host}_*.gz" -mtime +${keep_days} -exec ${rm} -f '{}' ';'
 log_and_exit_on_error "$?" 'Error' 'Unable to remove old PostgreSQL database dumps.'
 
 remove_lockfile
