fstrim: E: Improve Shell script to prevent globbing and word splitting

diff --git a/fstrim/templates/main/fstrim_discard-blocks.sh.j2 b/fstrim/templates/main/fstrim_discard-blocks.sh.j2
--- a/fstrim/templates/main/fstrim_discard-blocks.sh.j2
+++ b/fstrim/templates/main/fstrim_discard-blocks.sh.j2
@@ -51,7 +51,6 @@ fstrim=$(${which} fstrim) || { echo "Error: Command 'fstrim' not found."; exit 1
 
 host=$(${hostname} -s) || { echo "Error: Host name unknown."; exit 68; }
 script="$(${basename} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
-date_start=$(${date} '+%Y-%m-%dT%H:%M:%S%z')
 time_start=$(${date} '+%s')
 user='{{file_owner_fstrim_discard_blocks_sh}}'
 lockfile='{{file_dst_fstrim_script_dir}}/fstrim_discard-blocks.lock'
@@ -108,22 +107,22 @@ check_script_user() {
     retval=77
     severity='Error'
     message="Please run script as user '${user}'"
-    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: "${severity}: ${message}""
-    exit ${retval}
+    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
+    exit "${retval}"
   fi
 }
 
 create_lockfile() {
-  if [ ! -e ${lockfile} ]; then
-    ${touch} ${lockfile} || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
+  if [ ! -e "${lockfile}" ]; then
+    ${touch} "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
   else
     log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
   fi
 }
 
 remove_lockfile() {
-  if [ -e ${lockfile} ]; then
-    ${rm} -f ${lockfile} || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
+  if [ -e "${lockfile}" ]; then
+    ${rm} -f "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
   else
     log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
   fi
@@ -133,37 +132,32 @@ log_and_exit_on_error() {
   retval=$1
   severity=$2
   message=$3
-  if [ ${retval} -ne 0 ]; then
-    ${rm} -f ${lockfile}
-    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: "${severity}: ${message}""
-    ${logger} -t ${script} "${severity}: ${message}"
+  if [ "${retval}" -ne 0 ]; then
+    ${rm} -f "${lockfile}"
+    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
+    ${logger} -t "${script}" "${severity}: ${message}"
 {% if (fstrim_monitor_mail_state is match('true|yes|enable')) %}
-    mail_error ${retval} "${severity}" "${message}"
+    mail_error "${retval}" "${severity}" "${message}"
 {% endif %}
     add_log_header 'fstrim failed'
-
-    exit ${retval}
+    exit "${retval}"
   fi
 }
 
 log_and_exit() {
-  date_end=$(${date} '+%Y-%m-%dT%H:%M:%S%z')
   time_end=$(${date} '+%s')
-  time_exec=$(${expr} ${time_end} - ${time_start})
+  time_exec=$(${expr} "${time_end}" - "${time_start}")
   time_hr=$(${date} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
-
   retval=0
   severity='Info'
   message='Unused blocks discarded successfully.'
-  ${logger} -t ${script} "${severity}: ${message} Duration: ${time_hr}"
-
-  exit ${retval}
+  ${logger} -t "${script}" "${severity}: ${message} Duration: ${time_hr}"
+  exit "${retval}"
 }
 
 add_log_header() {
   name=$1
-
-  name_upper=$(${echo} ${name} | ${tr} '[:lower:]' '[:upper:]')
+  name_upper=$(${echo} "${name}" | ${tr} '[:lower:]' '[:upper:]')
   date_time=$(${date} '+%Y-%m-%dT%H:%M:%S%z')
   echo "
 #-------------------------------------------------------------------------------
